server:
  port: 6060

spring:
  config:
    import:
      - optional:classpath:application-secret.properties
  application:
    name: spring-boot-campus-assistant-api

  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_ai?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    # ?????
    hikari:
      maximum-pool-size: 10  # ?????
      minimum-idle: 5        # ??????
      idle-timeout: 300000   # ?????????5???
      connection-timeout: 20000  # ???????20??

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/api/v1
      read-timeout: 8000 # 读取超时时间，默认 8 秒
      chat:
        options:
          model: qwen-turbo
          # 基础参数：压缩计算量
          temperature: 0.2  # 设置输出随机性为中等程度
          seed: 123456  # 固定种子，避免重复推理
          top_p: 0.6 # 收集采样范围，加速解码
          top_k: 30 # 限制候选词数量
          max-tokens: 2000  # 控制输出长度
          repetition_penalty: 1.1 # 轻度去重，避免废话
          # 流式输出
          stream: true
          response_format: { type: "text" }
          tools: []
          tool-choice: "none"

# Knife4 ??
knife4j:
  enable: false
  setting:
    custom-code: 500
    enable-footer-custom: false

# JWT ???? application-secret.properties ???
jwt:
  secret: ${jwt.secret}
  expiration: ${jwt.expiration}