server:
  port: 8080

spring:
  config:
    import:
      - optional:classpath:application-secret.properties
  application:
    name: spring-boot-campus-assistant-api

  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_ai?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    # ?????
    hikari:
      maximum-pool-size: 10  # ?????
      minimum-idle: 5        # ??????
      idle-timeout: 300000   # ?????????5???
      connection-timeout: 20000  # ???????20??

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0


# Knife4 ??
knife4j:
  enable: false
  setting:
    custom-code: 500
    enable-footer-custom: false

# JWT ???? application-secret.properties ???
jwt:
  secret: ${jwt.secret}
  expiration: ${jwt.expiration}